 # Generated by Django 4.2 on 2023-06-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('v_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('v_country', models.CharField(max_length=64)),
                ('v_currency', models.CharField(max_length=64)),
                ('v_capitol', models.CharField(max_length=64)),
                ('v_language', models.CharField(max_length=32)),
                ('v_time_zone', models.CharField(max_length=32)),
                ('v_main_religion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('v_currency', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('v_countries', models.CharField(max_length=64)),
                ('v_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('v_religion', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_map', models.CharField(max_length=128)),
                ('v_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.country')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRateNBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_date', models.DateField()),
                ('v_currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.currency')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='v_currency_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='v_main_religion_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.religion'),
        ),
    ]
